import { dump as dumpYaml } from 'js-yaml';
import type { AgentsConfig } from '@synaptic-sentinel/core';

/**
 * Helpers para escribir `.sentinel/agents.yaml` desde el panel UI
 * (Phase 11 DG-074 B).
 *
 * Decision honesta sobre comentarios YAML: `js-yaml@4` NO preserva
 * comentarios al round-trip (es una limitacion conocida de la lib). Si
 * el usuario tiene comentarios en su `agents.yaml`, esta funcion los
 * pierde. Mitigacion: `agentsYamlHasComments` detecta su presencia y la
 * UI muestra una warning ANTES de invocar el writer. El usuario decide
 * si proceder o editar el YAML a mano.
 *
 * El YAML producido lleva un header con timestamp + nota de origen para
 * que el dev sepa que fue escrito por la extension (no confunda con
 * edicion manual).
 */

/** Detecta si el texto YAML contiene comentarios (lineas con `#`). */
export function agentsYamlHasComments(yamlText: string): boolean {
  const lines = yamlText.split('\n');

  // (1) Identifica el "header autogenerado": un bloque continuo de lineas
  // comentadas o vacias AL PRINCIPIO del archivo, encabezado por el
  // marcador `# Generated by SYNAPTIC`. Todas esas lineas se ignoran
  // (son nuestras, no del usuario).
  let headerEnd = 0;
  let firstNonEmpty: string | undefined;
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed === '') {
      headerEnd += 1;
      continue;
    }
    firstNonEmpty = trimmed;
    break;
  }
  const hasGeneratedHeader =
    firstNonEmpty !== undefined && firstNonEmpty.startsWith('# Generated by SYNAPTIC');
  if (hasGeneratedHeader) {
    for (let i = headerEnd; i < lines.length; i += 1) {
      const line = lines[i] as string;
      const trimmed = line.trim();
      if (trimmed === '' || trimmed.startsWith('#')) {
        headerEnd = i + 1;
        continue;
      }
      break;
    }
  } else {
    headerEnd = 0;
  }

  // (2) En el resto del archivo, cualquier comentario (linea-completa o
  // inline) cuenta como "del usuario".
  for (let i = headerEnd; i < lines.length; i += 1) {
    const line = lines[i] as string;
    const trimmed = line.trim();
    if (trimmed === '') continue;
    if (trimmed.startsWith('#')) {
      return true; // comentario de linea completa
    }
    const colonIdx = line.indexOf(':');
    const hashIdx = line.indexOf('#');
    if (hashIdx !== -1 && colonIdx !== -1 && hashIdx > colonIdx) {
      // Comentario inline. Heuristica buena-suficiente: si hay un `#`
      // despues del `:`, lo tratamos como comentario inline (un `#`
      // dentro de un string quoted queda mal clasificado, pero el
      // resultado es solo una warning, no perdida de datos).
      return true;
    }
  }
  return false;
}

/**
 * Serializa una `AgentsConfig` a `.sentinel/agents.yaml` con un header
 * autogenerado que documenta su origen.
 */
export function renderAgentsYaml(config: AgentsConfig): string {
  const header = [
    '# Generated by SYNAPTIC Sentinel — Brain Layer providers configuration.',
    '# Edit from the "Configure Brain Layer Providers" panel in VSCode',
    '# or by hand. The CLI reads this file at synaptic-sentinel triage.',
    '#',
    '# Providers: anthropic / openai / groq / deepseek / mistral / together /',
    '#            fireworks / perplexity / xai / gemini / bedrock / azure / ollama',
    '# API keys: NEVER live here — set SENTINEL_<PROVIDER>_API_KEY env vars',
    '#           or use VSCode SecretStorage via the panel.',
    '',
  ].join('\n');
  const body = dumpYaml(config, {
    indent: 2,
    lineWidth: 100,
    noRefs: true,
    sortKeys: false,
  });
  return header + body;
}
