import { describe, it, expect } from 'vitest';
import { parseAgentsConfigYaml, type AgentsConfig } from '@synaptic-sentinel/core';
import { agentsYamlHasComments, renderAgentsYaml } from '../src/agents-yaml-writer.js';

describe('agentsYamlHasComments', () => {
  it('devuelve false para un YAML sin comentarios', () => {
    const yaml = `agents:
  triage:
    provider: anthropic
    model: claude-haiku-4-5
  context:
    provider: anthropic
    model: claude-sonnet-4-6
  remediation:
    provider: anthropic
    model: claude-sonnet-4-6
`;
    expect(agentsYamlHasComments(yaml)).toBe(false);
  });

  it('detecta comentarios de linea completa', () => {
    const yaml = `# Brain Layer config
agents:
  triage:
    provider: anthropic
    model: claude-haiku-4-5
  context:
    provider: anthropic
    model: claude-sonnet-4-6
  remediation:
    provider: anthropic
    model: claude-sonnet-4-6
`;
    expect(agentsYamlHasComments(yaml)).toBe(true);
  });

  it('detecta comentarios inline', () => {
    const yaml = `agents:
  triage:
    provider: deepseek  # cheaper for mass triage
    model: deepseek-v3.2
  context:
    provider: anthropic
    model: claude-sonnet-4-6
  remediation:
    provider: anthropic
    model: claude-sonnet-4-6
`;
    expect(agentsYamlHasComments(yaml)).toBe(true);
  });

  it('ignora el header autogenerado por renderAgentsYaml', () => {
    // El header del renderer empieza con "# Generated by SYNAPTIC ..."
    // Lo trata como no-comentario-del-usuario para no warning sobre lo
    // que nosotros mismos escribimos.
    const yaml = `# Generated by SYNAPTIC Sentinel — Brain Layer providers configuration.
# Edit from the "Configure Brain Layer Providers" panel in VSCode
agents:
  triage:
    provider: anthropic
    model: claude-haiku-4-5
  context:
    provider: anthropic
    model: claude-sonnet-4-6
  remediation:
    provider: anthropic
    model: claude-sonnet-4-6
`;
    expect(agentsYamlHasComments(yaml)).toBe(false);
  });

  it('detecta un comentario user incluso si conviven con el header autogenerado', () => {
    const yaml = `# Generated by SYNAPTIC Sentinel — Brain Layer providers configuration.
agents:
  triage:
    # Edited by hand: cheaper triage
    provider: deepseek
    model: deepseek-v3.2
  context:
    provider: anthropic
    model: claude-sonnet-4-6
  remediation:
    provider: anthropic
    model: claude-sonnet-4-6
`;
    expect(agentsYamlHasComments(yaml)).toBe(true);
  });

  it('un YAML vacio o solo whitespace no tiene comentarios', () => {
    expect(agentsYamlHasComments('')).toBe(false);
    expect(agentsYamlHasComments('   \n\n\n')).toBe(false);
  });
});

describe('renderAgentsYaml', () => {
  const sampleConfig: AgentsConfig = {
    agents: {
      triage: { provider: 'deepseek', model: 'deepseek-v3.2' },
      context: { provider: 'anthropic', model: 'claude-sonnet-4-6' },
      remediation: { provider: 'anthropic', model: 'claude-opus-4-7' },
    },
  };

  it('incluye el header autogenerado al principio', () => {
    const yaml = renderAgentsYaml(sampleConfig);
    expect(yaml).toMatch(/^# Generated by SYNAPTIC Sentinel/);
  });

  it('produce YAML parseable que round-trippea a la misma config', () => {
    const yaml = renderAgentsYaml(sampleConfig);
    const parsed = parseAgentsConfigYaml(yaml);
    expect(parsed).toEqual(sampleConfig);
  });

  it('serializa baseUrl cuando esta presente', () => {
    const config: AgentsConfig = {
      agents: {
        triage: { provider: 'ollama', model: 'mistral-nemo:12b' },
        context: {
          provider: 'bedrock',
          model: 'anthropic.claude-opus-4',
          baseUrl: 'https://bedrock-mantle.us-east-1.api.aws/v1',
        },
        remediation: { provider: 'anthropic', model: 'claude-sonnet-4-6' },
      },
    };
    const yaml = renderAgentsYaml(config);
    expect(yaml).toContain('baseUrl');
    expect(yaml).toContain('bedrock-mantle');
    // Round-trip mantiene el baseUrl.
    const parsed = parseAgentsConfigYaml(yaml);
    expect(parsed.agents.context.baseUrl).toBe('https://bedrock-mantle.us-east-1.api.aws/v1');
  });

  it('documenta en el header que las API keys NUNCA viven en el YAML', () => {
    const yaml = renderAgentsYaml(sampleConfig);
    expect(yaml).toContain('API keys');
    expect(yaml).toContain('NEVER');
  });
});
